# Dev environment compose
services:
  # ---------------- db container ---------------- #
  db:
    image: fghub-db
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    container_name: fghub-db
    restart: always
    build:
      context: ./docker/db
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fghub
    ports:
      - 5432:5432

  # ---------------- server graph container ---------------- #
  server-graph:
    image: server-graph
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    container_name: server-graph
    restart: always
    build:
      context: .
      dockerfile: ./backend/api/graph/docker/dockerfile
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fghub
    depends_on:
      - db

  # ---------------- client fgapp container ---------------- #
  client-fgapp:
    image: client-fgapp
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    container_name: client-fgapp
    restart: always
    build:
      context: .
      dockerfile: ./frontend/fgapp/docker/dockerfile
    deploy:
      resources:
        limits:
          memory: 2048M
    depends_on:
      - server-graph

  # ---------------- nginx server container ---------------- #
  nginx:
    image: server-nginx
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    container_name: server-nginx
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
    build:
      context: ./docker/nginx/
    ports:
      - 80:80