FROM golang:1.18.3-alpine3.16

ENV APP_ENV dev
RUN apk update && apk upgrade

WORKDIR /app
COPY . ./
RUN go mod download
WORKDIR /app/backend/api/graph/
RUN go build -o /fghub-graph
EXPOSE 80

CMD ["/fghub-graph"]