// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewCharacter struct {
	Name   string `json:"name"`
	GameID string `json:"gameId"`
}

type NewGame struct {
	Slug     string `json:"slug"`
	Name     string `json:"name"`
	SeriesID string `json:"seriesId"`
}

type NewSeries struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
