// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCharacter struct {
	Name   string `json:"name"`
	GameID string `json:"gameId"`
}

type NewGame struct {
	Slug     string `json:"slug"`
	Name     string `json:"name"`
	SeriesID string `json:"seriesId"`
}

type NewSeries struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}
