// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCharacter struct {
	Name string `json:"name"`
}

type NewGame struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
