FROM golang:1.18.3-alpine3.16

ENV APP_ENV dev
RUN apk update && apk upgrade

WORKDIR /app
COPY . ./
RUN go mod download
WORKDIR /app/frontend/fgapp/
RUN GOOS=js GOARCH=wasm go build -o web/assets/app.wasm && go build -o bin/server

CMD ["./bin/server"]